batch_size: 128
dropout_rate: 0.0
early_stopping_patience: 5
global_features: []
heads: 1
hidden_channels: 64
hidden_size: 64
knns: 0
learning_rate: 1.0e-05
look_back_hours: 12
lstm_hidden_size: 64
max_epochs: 25
model_architecture: mlp
num_gnn_layers: 2
num_hidden_layers: 1
num_lstm_layers: 2
optimizer: Adam
resolution: 10min
station_features:
- wind_speed
- wind_direction_sin
- wind_direction_cos
- relative_humidity
station_ids:
- 03897
- 01759
- '06163'
- '05516'
- 05930
- '04271'
- 00183
- '03032'
- 04393
- 02429
- '04625'
- 00591
- 01694
- 01975
- 04039
- 03093
- '04466'
- 02907
- '04642'
- '02115'
use_global_scaling: false
use_residual: true
weighting: distance
