batch_size: 128
dense_hidden_size: 64
dropout_rate: 0.0
early_stopping_patience: 5
global_features:
- sin_1d
- cos_1d
- sin_1y
- cos_1y
heads: 2
hidden_channels: 128
knns: 0
learning_rate: 1.0e-05
look_back_hours: 5
lstm_hidden_size: 256
max_epochs: 25
model_architecture: mlp
num_hidden_dense_layers: 2
num_hidden_gnn_layers: 2
num_hidden_lstm_layers: 1
optimizer: Adam
resolution: 30min
station_features:
- wind_speed
- wind_direction_sin
- wind_direction_cos
- air_pressure
- relative_humidity
station_ids:
- '00342'
- '00662'
- '00704'
- 00891
- 00963
- '01503'
- 01691
- '02014'
- 03093
- '04745'
- '07367'
- '02115'
- 00691
- '01544'
- '07374'
- 01975
- '01766'
use_global_scaling: true
use_residual: true
weighting: distance
