batch_size: 128
learning_rate: 1.0e-05
early_stopping_patience: 5
max_epochs: 25
optimizer: Adam

# possible mlp, lstm, gcn, gcn_lstm, (gat); the GAT is only experimental and used in the thesis
model_architecture: mlp 

dense_hidden_size: 64
num_hidden_dense_layers: 2

lstm_hidden_size: 256  
num_hidden_lstm_layers: 1

hidden_channels: 128
num_hidden_gnn_layers: 2

# whether the graph-based models use residual connection
use_residual: true

# weighting method to build graph for graph-based models
# thesis uses 'distance'; 'similarity' is experimental
weighting: distance 

# number of nearest neighbors for graph building
# 0 means complete graph; everything else is experimental
knns: 0 

# number of attention heads for GAT
heads: 2 

dropout_rate: 0.0

# features
global_features:
- sin_1d
- cos_1d 
- sin_1y 
- cos_1y  
station_features:  
- wind_speed  
- wind_direction_sin  
- wind_direction_cos  
- air_pressure  
- air_temperature 

# If true fit scalers for all stations combined and per station otherwise. Thesis uses True.
use_global_scaling: true 

# temporal config
look_back_hours: 3  
resolution: 10min

# spatial config
station_ids:
- "00342"
- "00662"
- "00704"
- "00891"
- "00963"
- "01503"
- "01691"
- "02014"
- "03093"
- "04745"
- "07367"
- "02115"
- "00691"
- "01544"
- "07374"
- "01975"
- "01766"

