batch_size: 128
dropout_rate: 0.0
early_stopping_patience: 5
global_features: []
heads: 1
hidden_channels: 64
hidden_size: 64
knns: 4
learning_rate: 1.0e-05
look_back_hours: 12
lstm_hidden_size: 64
max_epochs: 25
model_architecture: mlp
num_gnn_layers: 2
num_hidden_layers: 1
num_lstm_layers: 2
optimizer: Adam
resolution: 1h
station_features:
- wind_speed
- wind_direction_sin
- wind_direction_cos
station_ids:
- "03897"
use_global_scaling: true
use_residual: true
weighting: distance
