# Learning config
batch_size: 128
learning_rate: 0.00001
optimizer: Adam

# Architecture config
hidden_size: 128
model_architecture: mlp
num_hidden_layers: 3
dropout_rate: 0.0

# Spatial config
station_ids:
- "03897"

# Temporal config
resolution: 10min
look_back_hours: 1

# Feature selection
global_features:
- hour_sin

station_features:
- wind_speed
