batch_size: 128
dropout_rate: 0.0
early_stopping_patience: 5
global_features:
- sin_1d
- cos_1d
heads: 1
hidden_channels: 64
hidden_size: 64
knns: 0
learning_rate: 1.0e-05
look_back_hours: 12
lstm_hidden_size: 64
max_epochs: 25
model_architecture: mlp
num_gnn_layers: 2
num_hidden_layers: 1
num_lstm_layers: 2
optimizer: Adam
resolution: 10min
station_features:
- wind_speed
- wind_direction_sin
- wind_direction_cos
station_ids:
- '00342'
- '00656'
- '00662'
- '00704'
- 00891
- 00963
- '01503'
- 01691
- '02014'
- 03093
- '03631'
- '04745'
- '07367'
- '02115'
- 00691
- '00701'
- '01544'
- '07374'
- 01975
- '01766'
use_global_scaling: false
use_residual: true
weighting: distance
