batch_size: 128
dense_hidden_size: 32
dropout_rate: 0.0
early_stopping_patience: 5
global_features:
- sin_1d
- cos_1d
- sin_1y
- cos_1y
heads: 2
hidden_channels: 128
knns: 0
learning_rate: 1.0e-05
look_back_hours: 4
lstm_hidden_size: 256
max_epochs: 25
model_architecture: gcn_lstm
num_hidden_dense_layers: 0
num_hidden_gnn_layers: 2
num_hidden_lstm_layers: 1
optimizer: Adam
resolution: 30min
station_features:
- wind_speed
- wind_direction_sin
- wind_direction_cos
- air_pressure
- air_temperature
station_ids:
- '04745'
- '02014'
- 00691
- '00704'
- 01975
- '00662'
use_global_scaling: true
use_residual: true
weighting: distance
